<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2013-03-04 14:07

$extensionClassesPath = t3lib_extMgm::extPath('dd_download') . 'Classes/';
return array(
	'tx_dddownload_controller_filecontroller' => $extensionClassesPath . 'Controller/FileController.php',
	'tx_dddownload_domain_model_category' => $extensionClassesPath . 'Domain/Model/Category.php',
	'tx_dddownload_domain_model_file' => $extensionClassesPath . 'Domain/Model/File.php',
	'tx_dddownload_domain_repository_filerepository' => $extensionClassesPath . 'Domain/Repository/FileRepository.php',
	'tx_dddownload_viewhelpers_filesizeviewhelper' => $extensionClassesPath . 'ViewHelpers/FilesizeViewHelper.php',
);
?>